# Generated by Django 4.2.23 on 2025-08-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_alter_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='bank_account',
            field=models.CharField(blank=True, db_column='BankAccount', max_length=50, null=True),
        ),
    ]
