# Generated by Django 4.2.23 on 2025-09-03 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        ('location', '0020_healthfacility_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacilityContract',
            fields=[
                ('id', models.AutoField(db_column='HFContractId', primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_column='StartDate')),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('validity_from', models.DateTimeField(blank=True, db_column='ValidityFrom', null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserId', null=True)),
                ('created_by', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_hf_contracts', to='core.interactiveuser')),
                ('health_facility', models.ForeignKey(db_column='HFID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts', to='location.healthfacility')),
                ('location', models.ForeignKey(db_column='LocationId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='hf_contracts', to='location.location')),
            ],
            options={
                'db_table': 'tblHFContract',
                'managed': True,
                'indexes': [models.Index(fields=['location', 'health_facility', 'start_date', 'end_date'], name='hf_contract_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='healthfacilitycontract',
            constraint=models.UniqueConstraint(fields=('health_facility', 'location', 'validity_to'), name='uq_hf_loc_contract_valid'),
        ),
    ]
