# Generated by Django 4.2.23 on 2025-09-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0021_healthfacilitycontract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilitycontract',
            name='end_date',
            field=models.DateTimeField(blank=True, db_column='EndDate', null=True),
        ),
        migrations.AlterField(
            model_name='healthfacilitycontract',
            name='start_date',
            field=models.DateTimeField(db_column='StartDate'),
        ),
    ]
