# Generated by Django 4.2.23 on 2025-09-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_alter_healthfacilitycontract_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='healthfacilitycontract',
            name='uq_hf_loc_contract_valid',
        ),
        migrations.RemoveField(
            model_name='healthfacilitycontract',
            name='validity_from',
        ),
        migrations.RemoveField(
            model_name='healthfacilitycontract',
            name='validity_to',
        ),
        migrations.AddConstraint(
            model_name='healthfacilitycontract',
            constraint=models.UniqueConstraint(fields=('health_facility', 'location'), name='uq_hf_loc_contract'),
        ),
    ]
