# Generated by Django 4.2.26 on 2025-12-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_location_bank_account'),
        ('location', '0023_remove_healthfacilitycontract_uq_hf_loc_contract_valid_and_more'),
    ]

    operations = [
    ]
