# Generated by Django 4.2.26 on 2025-12-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_pricelist', '0005_laboratoryservicespricelist_and_more'),
        ('location', '0024_merge_20251225_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='lab_services_pricelist',
            field=models.ForeignKey(blank=True, db_column='PLLabServiceID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='health_facilities', to='medical_pricelist.laboratoryservicespricelist'),
        ),
    ]
